In [1]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt





df=pd.read_csv("/content/glass (1).csv")
print("dataset",df)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df))

x=df.drop('Type',axis=1)
y=df.Type

dataset       Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe  Type
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 11 columns]
[[-1.72397593  0.87286765  0.28495326 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.707788

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


from sklearn import svm
ml=svm.SVC(kernel='linear')
ml.fit(x_train,y_train)


print(ml.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.76000e+02 1.52119e+00 1.29700e+01 3.30000e-01 1.51000e+00 7.33900e+01
  1.30000e-01 1.12700e+01 0.00000e+00 2.80000e-01]


In [3]:
print(ml.n_support_)

[1 2 2 4 3 2]


In [4]:
y_pred=ml.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy Score",accuracy_score(y_test,y_pred))

print("Confusion Matrix",confusion_matrix(y_test,y_pred))

print("Classification Report\n",classification_report(y_test,y_pred))

Accuracy Score 1.0
Confusion Matrix [[22  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]
Classification Report
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        22
           2       1.00      1.00      1.00        26
           3       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [5]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

#With Different Kernels

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [6]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

print("Accuracy Score of kernel 1",accuracy_score(y_test,ypred1))

print("Accuracy Score of kernel 2",accuracy_score(y_test,ypred2))

print("Accuracy Score of kernel 3",accuracy_score(y_test,ypred3))

Accuracy Score of kernel 1 0.6923076923076923
Accuracy Score of kernel 2 0.9384615384615385
Accuracy Score of kernel 3 0.8461538461538461
